auth/urls.py
from django.conf.urls import *
from django.contrib.auth import *

urlpatterns = patterns('',
    (r'^create/*$', 'votefinder.auth.views.create_step_1'),
    (r'^create/2/*$', 'votefinder.auth.views.create_step_2'),
    (r'^create/done/*$', 'votefinder.auth.views.create_step_3'),
    (r'^login/*$',   'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    (r'^logout/*$',  'django.contrib.auth.views.logout', {'template_name': 'logged_out.html'}),
    (r'^password_change/*$', 'django.contrib.auth.views.password_change', {'template_name': 'password_change_form.html', 'post_change_redirect': 'done/'}),
    (r'^password_change/done/*$', 'django.contrib.auth.views.password_change_done', {'template_name': 'password_change_done.html'}),
    (r'^password_reset/$',
        'django.contrib.auth.views.password_reset',
        {'post_reset_redirect' : 'done/','template_name': 'password_reset_form.html'}),
    (r'^password_reset/done/$',
        'django.contrib.auth.views.password_reset_done', {'template_name': 'password_reset_done.html'}),
    url(r'^password_reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect' : '/password_reset/complete/', 'template_name': 'password_reset_confirm.html'}, name="password_reset_confirm"),
    (r'^password_reset/complete/$',
        'django.contrib.auth.views.password_reset_complete', {'template_name': 'password_reset_complete.html'}),
)


votefinder/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.contrib import admin
from django.views import static
from votefinder.main import urls as main_urls
from votefinder.vfauth import urls as auth_urls

admin.autodiscover()

urlpatterns = [
    path('auth/', include(auth_urls)),
    path('admin/', admin.site.urls),
    path('', include(main_urls)),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}),
    ]

votefinder/vfauth/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as django_views
from votefinder.vfauth import views as auth_views

urlpatterns = [
    path('link_profile', auth_views.give_user_profile_key),
    re_path(r'link_profile/2/*$', auth_views.link_profile),
    re_path(r'link_profile/done/*$', auth_views.link_user_to_profile),
    path('create', auth_views.create_votefinder_account),
    re_path(r'create/done/*$', auth_views.validate_and_create_user),
    path('login', django_views.LoginView.as_view(template_name='login.html')),
    path('logout', django_views.LogoutView.as_view(template_name='logged_out.html')),
    path('password_change/', django_views.PasswordChangeView.as_view(template_name='password_change_form.html', success_url='done/')),
    path('password_change/done/', django_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html')),
    path('password_reset/',
         django_views.PasswordResetView.as_view(success_url='done/', template_name='password_reset_form.html')),
    path('password_reset/done/',
         django_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html')),
    re_path(r'^password_reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
            django_views.PasswordResetConfirmView.as_view(success_url='/auth/password_reset/complete/', template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset/complete/',
         django_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html')),
]

votefinder/vfauth/models.py
import re
import urllib

from django import forms
from django.contrib.auth.models import User
from votefinder.main.BNRApi import BNRApi
from votefinder.main.SAForumPageDownloader import SAForumPageDownloader
from votefinder.main.models import Player, UserProfile


class CreateUserForm(forms.Form):
    login = forms.CharField(label='Username', min_length=3)
    email = forms.EmailField(label='Email')
    password = forms.CharField(widget=forms.PasswordInput, min_length=5,
                               label='New Password')
    confirm = forms.CharField(widget=forms.PasswordInput, min_length=5,
                              label='Confirm Password')

    def clean_login(self):
        login = self.cleaned_data['login']
        try:
            existing_user = User.objects.all().get(username=login)
            raise forms.ValidationError('A user by the name {} already exists.'.format(existing_user.username))
        except User.DoesNotExist:
            pass  # noqa: WPS420
        return login

    def clean_confirm(self):
        password1 = self.cleaned_data['password']
        password2 = self.cleaned_data['confirm']
        if password1 != password2:
            raise forms.ValidationError("The two password fields don't match.")
        return password2


class LinkProfileForm(forms.Form):
    login = forms.CharField(label='Username', min_length=3)
    home_forum = forms.ChoiceField(choices=[('sa', 'Something Awful'), ('bnr', 'Bread & Roses')])

    def clean_login(self):
        login = self.cleaned_data['login']
        home_forum = self.data['home_forum']

        if self.required_key:
            if home_forum == 'sa':
                downloader = SAForumPageDownloader()
                page_data = downloader.download(
                    'https://forums.somethingawful.com/member.php?action=getinfo&username={}'.format(urllib.parse.quote_plus(login)))

                if page_data is None:
                    raise forms.ValidationError('There was a problem downloading the profile for the SA user {}.'.format(login))

                if page_data.find(str(self.required_key)) == -1:
                    raise forms.ValidationError("Unable to find the correct key ({}) in {}'s SA profile".format(self.required_key, login))
                else:
                    matcher = re.compile(r'userid=(?P<userid>\d+)').search(page_data)
                    if matcher:
                        self.userid = matcher.group('userid')
                        try:
                            existing_player = Player.objects.all().get(sa_uid=self.userid)
                            existing_userprofile = UserProfile.objects.all().get(player=existing_player)  # noqa: F841
                            raise forms.ValidationError('{} is already registered to a user profile. Do you have another Votefinder account?'.format(existing_player.name))
                        except Player.DoesNotExist:
                            pass  # noqa: WPS420
                        except UserProfile.DoesNotExist:
                            raise forms.ValidationError('Votefinder is already aware of {} as an unclaimed player profile. Claim it from their <a href="/player/{}">profile page</a>.'.format(existing_player.name, existing_player.slug))
                        matcher = re.compile(r'\<dt class="author"\>(?P<login>.+?)\</dt\>').search(page_data)
                        if matcher:
                            login = matcher.group('login')
                    else:
                        raise forms.ValidationError(
                            'Unable to find the userID of {}.  Please talk to the site admin.'.format(login))
            elif home_forum == 'bnr':
                api = BNRApi()
                user_profile = api.get_user_by_name(urllib.parse.quote_plus(login))
                if user_profile is None:
                    raise forms.ValidationError('There was a problem downloading the profile for the BNR user {}.'.format(login))
                if user_profile['location'] == str(self.required_key):
                    if user_profile['user_id']:
                        self.userid = user_profile['user_id']
                        try:
                            existing_player = Player.objects.all().get(bnr_uid=self.userid)
                            raise forms.ValidationError('{} is already registered with that user ID. Has your forum name changed?'.format(existing_player.name))
                        except Player.DoesNotExist:
                            pass  # noqa: WPS420
                        login = user_profile['username']
                    else:
                        raise forms.ValidationError(
                            'Unable to find the userID of {}.  Please talk to the site admin.'.format(login))
                else:
                    raise forms.ValidationError("Unable to find the correct key ({}) in {}'s BNR profile".format(self.required_key, login))

        return login

votefinder/vfauth/views.py
import random

from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template.context_processors import csrf
from votefinder.main.models import Player, UserProfile
from votefinder.vfauth.models import CreateUserForm, LinkProfileForm


def give_user_profile_key(request):
    profile_key = random.randint(10000000, 99999999)  # noqa: S311
    request.session['profileKey'] = profile_key
    return render(request, 'step1.html', {'profileKey': profile_key})


def create_votefinder_account(request):
    form = CreateUserForm()
    return render(request, 'create_user_form.html', {'form': form})


@login_required
def link_profile(request):
    key = request.session['profileKey']
    if not key:
        return HttpResponseRedirect('auth/link_profile')
    form = LinkProfileForm()
    return render(request, 'link_profile_form.html', {'form': form})


def create_user(login, email, password):
    user = User.objects.create_user(login, email, password)
    user.save()
    return user


def validate_and_create_user(request):
    if request.method != 'POST':
        return HttpResponseRedirect('/auth/create')

    csrf_resp = {}
    csrf_resp.update(csrf(request))

    form = CreateUserForm(request.POST)

    if form.is_valid():
        user = create_user(form.cleaned_data['login'], form.cleaned_data['email'], form.cleaned_data['password'])
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        login(request, user)
        player = Player.objects.create(name=request.user.username)
        profile = UserProfile(player=player, user=request.user)
        profile.save()
        messages.add_message(request, messages.SUCCESS,
                             '<strong>Done!</strong> Your account was created and you are now logged in.')
        return HttpResponseRedirect('/')
    return render(request, 'create_user_form.html', {'form': form})


@login_required
def link_user_to_profile(request):
    key = request.session['profileKey']
    if not key or request.method != 'POST':
        return HttpResponseRedirect('/auth/link_profile')
    csrf_resp = {}
    csrf_resp.update(csrf(request))

    form = LinkProfileForm(request.POST)
    form.required_key = key
    if form.is_valid():
        player = request.user.profile.player
        if player is not None:
            if form.cleaned_data['home_forum'] == 'sa':
                player.sa_uid = form.userid
            elif form.cleaned_data['home_forum'] == 'bnr':
                player.bnr_uid = form.userid
            player.save()
        messages.add_message(request, messages.SUCCESS, '<strong>Done!</strong> Your forum profile was successfully linked.')
        return HttpResponseRedirect('/profile')
    return render(request, 'link_profile_form.html', {'form': form})

votefinder/vfauth/templates/create_user_form.html
{% extends "base.html" %}
{% block title %}Votefinder: Register Account{% endblock %}

{% block onready %}
    $('#submitButton').button().click(function(){
    $('#submitButton').attr("disabled", "disabled");
    $('#createUserForm').submit();
    });
{% endblock %}

{% block content %}
    <h1><a href="/">Votefinder</a>: Create Account</h1>
    <hr>
    <p>Enter the login information you'd like to use for the Votefinder site.</p>
    <p>Your e-mail address will only be used if you forget your password.</p>
    <p>
        <form id="createUserForm" action="/auth/create/done/" method="post">{% csrf_token %}
            <table border="0" cellpadding="3" cellspacing="2">
                <tr class="fieldWrapper">
                    <td><label for="id_login">Votefinder Username:</label></td>
                    <td>{{ form.login }}</td>
                    <td>{{ form.login.errors|safe }}</td>
                </tr>
                <tr class="fieldWrapper">
                    <td><label for="id_email">Email Address:</label></td>
                    <td>{{ form.email }}</td>
                    <td>{{ form.email.errors }}</td>
                </tr>
                <tr class="fieldWrapper">
                    <td><label for="id_password">New Password:</label></td>
                    <td>{{ form.password }}</td>
                    <td>{{ form.password.errors }}</td>
                </tr>
                <tr class="fieldWrapper">
                    <td><label for="id_confirm">Confirm Password:</label></td>
                    <td>{{ form.confirm }}</td>
                    <td>{{ form.confirm.errors }}</td>
                </tr>
            </table>
    <p><input id="submitButton" type="Submit" value="Complete &raquo;"/></p>
    </form>
    </p>

{% endblock %}

votefinder/vfauth/templates/done.html
{% extends "base.html" %}
{% block title %}Votefinder: Account Created{% endblock %}

{% block content %}
    <h1><a href="/">Votefinder</a>: Account Created</h1>
    <hr>

    <p>Your account is created and you are now logged in.
        <a href="/">Click here</a> to go back to the main site.</p>
{% endblock %}

votefinder/vfauth/templates/link_profile_form.html
{% extends "base.html" %}
{% block title %}Votefinder: Link Forums Profile{% endblock %}

{% block onready %}
    $('#submitButton').button().click(function(){
    $('#submitButton').attr("disabled", "disabled");
    $('#linkProfileForm').submit();
    });
{% endblock %}

{% block content %}
    <h1><a href="/">Votefinder</a>: Link Forums Profile, Step 2</h1>
    <hr>
    <p>Now, enter your user name and home forum.</p>
    <p>
        <form id="linkProfileForm" action="/auth/link_profile/done/" method="post">{% csrf_token %}
            <table border="0" cellpadding="3" cellspacing="2">
                <tr class="fieldWrapper">
                    <td><label for="id_login">Forum Username:</label></td>
                    <td>{{ form.login }}</td>
                    <td>{{ form.login.errors|safe }}</td>
                </tr>
                <tr class="fieldWrapper">
                    <td><label for="id_home_forum">Home Forum:</label></td>
                    <td>{{ form.home_forum }}</td>
                    <td>{{ form.home_forum.errors }}</td>
                </tr>
            </table>
    <p><input id="submitButton" type="Submit" value="Complete &raquo;"/></p>
    </form>
    </p>

{% endblock %}

votefinder/vfauth/templates/logged_out.html
{% extends "base.html" %}
{% block title %}Votefinder: Logged Out{% endblock %}

{% block content %}
    <h1><a href="/">Votefinder</a>: Logged Out</h1>
    <hr>

    <p>You have been logged out and your session variables cleared.
        <a href="/">Click here</a> to go back to the main site, or <a href="/auth/login">log back in</a>.</p>
{% endblock %}

votefinder/vfauth/templates/login.html
{% extends "base.html" %}
{% block title %}Votefinder: Log In{% endblock %}

{% block onready %}
    $("button, input:submit").button();
{% endblock %}

{% block content %}
    <h1><a href="/">Votefinder</a>: Log In</h1>
    <hr>

    <p>Enter your user information. If you don't have an account, you may <a href="/auth/create">create one</a>.</p>

    {% if form.non_field_errors %}
        <p>
            {% for error in form.non_field_errors %}
                <strong>Error:</strong> {{ error }}
            {% endfor %}
            <a href="/auth/password_reset/">Forgot your password?</a>
        </p>
    {% endif %}

    <form action="/auth/login{% if next and next != '/auth/logout' %}?next={{ next }}{% endif %}" method="post">{% csrf_token %}
        <table border="0" cellpadding="3" cellspacing="2">
            <tr>
                <td>Username:</td>
                <td>{{ form.username }}</td>
                <td>{{ form.username.errors }}</td>
            </tr>
            <tr>
                <td>Password:</td>
                <td>{{ form.password }}</td>
                <td>{{ form.password.errors }}</td>
            </tr>
        </table>

        <p><input type="Submit" value="Login"/></p>
    </form>

{% endblock %}

votefinder/vfauth/templates/password_change_done.html
{% extends "base.html" %}
{% block title %}Votefinder: Password Change{% endblock %}

{% block content %}
    <h1><a href="/">Votefinder</a>: Password Changed</h1>
    <hr>

    <p>Your password was changed, please don't forget it!</p>
    <p><a href="/">Click here</a> to go back to the main site.</p>
{% endblock %}

votefinder/vfauth/templates/password_change_form.html
{% extends "base.html" %}
{% block title %}Votefinder: Change Password{% endblock %}

{% block onready %}
    $("button, input:submit").button();
{% endblock %}

{% block content %}
    <h1><a href="/">Votefinder</a>: Change Password</h1>
    <hr>

    <p>From this page you can change your password.</p>

    <form action="/auth/password_change/" method="post">{% csrf_token %}
        <table border="0" cellpadding="3" cellspacing="2">
            <tr>
                <td>Old Password:</td>
                <td>{{ form.old_password }}</td>
                <td>{{ form.old_password.errors }}</td>
            </tr>
            <tr>
                <td>New Password:</td>
                <td>{{ form.new_password1 }}</td>
                <td>{{ form.new_password1.errors }}</td>
            </tr>
            <tr>
                <td>Confirm New Password:</td>
                <td>{{ form.new_password2 }}</td>
                <td>{{ form.new_password2.errors }}</td>
            </tr>
        </table>

        <p><input type="Submit" value="Change Password"/></p>
    </form>

{% endblock %}

votefinder/vfauth/templates/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Votefinder: Password Reset Complete{% endblock %}

{% block content %}
    <h1><a href="/">Votefinder</a>: Password Reset Complete</h1>
    <hr>

    <p>Your password has been set. You may go ahead and log in now.</p>
    <p><a href="/auth/login">Log in</a></p>
{% endblock %}

votefinder/vfauth/templates/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Votefinder: Change Password{% endblock %}

{% block onready %}
    $("button, input:submit").button();
{% endblock %}

{% block content %}
    <h1><a href="/">Votefinder</a>: Reset Password</h1>
    <hr>

    <p>Please enter your new password twice so we can verify you typed it in correctly.</p>


    <form action method="post">{% csrf_token %}
        <table border="0" cellpadding="3" cellspacing="2">
            <tr>
                <td>New Password:</td>
                <td>{{ form.new_password1 }}</td>
                <td>{{ form.new_password1.errors }}</td>
            </tr>
            <tr>
                <td>Confirm New Password:</td>
                <td>{{ form.new_password2 }}</td>
                <td>{{ form.new_password2.errors }}</td>
            </tr>
        </table>
        <p><input type="Submit" value="Change Password"/></p>

    </form>
{% endblock %}

votefinder/vfauth/templates/password_reset_done.html
{% extends "base.html" %}
{% block title %}Votefinder: Password Reset Request{% endblock %}

{% block content %}
    <h1><a href="/">Votefinder</a>: Password Reset Request</h1>
    <hr>

    <p>Instructions have been sent to your email on file to reset your password. Please check your email and follow the
        enclosed instructions.</p>
    <p><a href="/">Click here</a> to go back to the main site.</p>
{% endblock %}

votefinder/vfauth/templates/password_reset_form.html
{% extends "base.html" %}
{% block title %}Votefinder: Reset Password{% endblock %}

{% block onready %}
    $("button, input:submit").button();
{% endblock %}

{% block content %}
    <h1><a href="/">Votefinder</a>: Change Password</h1>
    <hr>

    <p>Forgotten your password? Enter your e-mail address below, and we'll e-mail instructions for setting a new
        one.</p>

    <form action="/auth/password_reset/" method="post">{% csrf_token %}
        <table border="0" cellpadding="3" cellspacing="2">
            <tr>
                <td>Email Address:</td>
                <td>{{ form.email }}</td>
                <td>{{ form.email.errors }}</td>
            </tr>
        </table>

        <p><input type="Submit" value="Change Password"/></p>
    </form>

{% endblock %}

votefinder/vfauth/templates/step1.html
{% extends "base.html" %}
{% block title %}Votefinder: Link Forum Profile, Step 1{% endblock %}

{% block onready %}
{% endblock %}

{% block content %}
    <h1><a href="/">Votefinder</a>: Link Forum Profile, Step 1</h1>
    <hr>

    <p>Open your <a href="https://forums.somethingawful.com/member.php?action=editprofile" target="_blank">SA Forums
        Profile</a> or your <a href="https://breadnroses.net/account/account-details" target="_blank">Bread and Roses account details page</a> (link opens a new window).</p>

    <p><b>Something Awful users:</b> In the Location, Interests, or Occupation field, paste this value: <strong>{{ profileKey }}</strong><br/>
        Save your profile then press Next on this page to continue to step 2.</p>
    <p><b>Bread and Roses users:</b> In the Location field, paste this value: <strong>{{ profileKey }}</strong></p>

    <a href="/auth/link_profile/2/">Continue &raquo;</a>
{% endblock %}

votefinder/vfauth/templates/step2.html
{% extends "base.html" %}
{% block title %}VoteFinder: Register Account, Step 2{% endblock %}

{% block onready %}
    $('#submitButton').button().click(function(){
    $('#submitButton').attr("disabled", "disabled");
    $('#createUserForm').submit();
    });
{% endblock %}

{% block content %}
    <h1><a href="/">VoteFinder</a>: Create Account: Step 2</h1>
    <hr>
    <p>Now, enter the login information you'd like to use for the VoteFinder site.
        <strong>Your username must match your SA username!</strong> Your password should not match!
    </p>
    <p>Your e-mail address will only be used if you forget your password.</p>
    <p>
        <form id="createUserForm" action="/auth/create/done/" method="post">{% csrf_token %}
            <table border="0" cellpadding="3" cellspacing="2">
                <tr class="fieldWrapper">
                    <td><label for="id_login">SA Username:</label></td>
                    <td>{{ form.login }}</td>
                    <td>{{ form.login.errors|safe }}</td>
                </tr>
                <tr class="fieldWrapper">
                    <td><label for="id_email">Email Address:</label></td>
                    <td>{{ form.email }}</td>
                    <td>{{ form.email.errors }}</td>
                </tr>
                <tr class="fieldWrapper">
                    <td><label for="id_password">New Password:</label></td>
                    <td>{{ form.password }}</td>
                    <td>{{ form.password.errors }}</td>
                </tr>
                <tr class="fieldWrapper">
                    <td><label for="id_confirm">Confirm Password:</label></td>
                    <td>{{ form.confirm }}</td>
                    <td>{{ form.confirm.errors }}</td>
                </tr>
            </table>
    <p><input id="submitButton" type="Submit" value="Complete &raquo;"/></p>
    </form>
    </p>

{% endblock %}